### PR TITLE
Errors to eventlog

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Comment by viktordick** [comment]
Sorry, this PR was meant to go against our fork. I am not sure if you are still interested in maintaining this? We have changed quite a lot since you started this project for us.

**Comment by icemac** [comment]
@viktordick You (PerFact) should probably own the canonical version of the repository.
The easiest way is probably to archive our repository. (Alternatively we could migrate it over to the perfact organization but this a difficult process as repositories can only be moved between persons not organizations.)

What did do you think?

**Comment by viktordick** [comment]
@icemac Yes, archiving would probably be best. Assuming this will break the "forked from" link on github - will it?

**Comment by icemac** [comment]
@viktordick No it should not break that link as it only switches the repository to a read-only state.

**Pull request closed without merging**
